# Generated by Django 5.2.4 on 2025-08-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_employees_e_departm_99b42d_idx_and_more"),
    ]

    operations = []
