# Generated by Django 5.2.4 on 2025-08-13 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0003_employee_employees_e_departm_99b42d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='rating',
            field=models.IntegerField(help_text='Rating must be between 1 and 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('employee', 'review_date')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance__date_61f2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_132c06_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['employee', 'review_date'], name='attendance__employe_dfc441_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['rating'], name='attendance__rating_518c92_idx'),
        ),
    ]
